apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab13b-nginx-deployment
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: gmanos/lab13b:nginx.nowy
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "25Mi"
              cpu: "300m"
            limits:
              memory: "50Mi"
              cpu: "500m"
