apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab13b-nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: gmanos/lab13b:nginx.stary
          ports:
            - containerPort: 80
